### ISSUE TITLE
Stuck Transactions On Large Broadcast of UTXO Chain

### ISSUE THREAD

**Issue by cchrysostom** [floblockchain/flo#12] opened 2019-03-15 21:49 UTC
### Stuck Transactions during Large Broadcast of UTXO Chain

1. "Stuck" transactions can happen under certain conditions where peers have their mempool full and the rest of the ancestor chain does not get added to the next block.
2. "Stuck" transactions need to be re-broadcasted by process defined in all implementations of FLO where a user interacts with the chain directly (qt, js-oip, etc).

Before proceeding with this upgrade described in this [pull request](https://github.com/floblockchain/flo/pull/8), we should know the answer to these questions:

1. Under what conditions do transactions get stuck due to mempool issues?
2. If a client generates a transaction that has ancestors above the allowed limit, does it accept that transaction into its own mempool?
3. How do other nodes react to a node broadcasting a transaction in question (2) above?

**Comment by OstlerDev** [comment] 2019-04-25 21:26
I just witnessed a rebroadcast of unconfirmed wallet transactions upon FLOcore being restarted. So it seems like some rebroadcast functionality might work, but only after a restart. It might be good to get it working without a restart as well.

**Comment by OstlerDev** [comment] 2024-04-18 23:11
Since we have merged https://github.com/floblockchain/flo/pull/8 I think we are safe to close this :) Just tidying up.

Btw, hi Chris!

**Closed as completed by OstlerDev** 2024-04-18 23:11 UTC
